### ISSUE TITLE
Great work ! When will be  the  pretrained models published

### ISSUE THREAD

**Issue by cavalry7131** [OpenImagingLab/DualDn#4]
Great work ! When will be  the  pretrained models published

**Comment by Lyricccco** [comment]
THQ for your attention. I will finish the uploading in a day or two, please keep in torch. :)

**Comment by Lyricccco** [comment]
> Great work ! When will be the pretrained models published

THQ for your attention. I will finish the uploading in a day or two, please keep in torch. :)

**Comment by profile838** [comment]
Yes, please upload model :) I am so curious to try project. :)
Thanks

**Comment by profile838** [comment]
Okay, model is here, but not instructions how to use it on own imagees.

**Comment by Lyricccco** [comment]
> Okay, model is here, but not instructions how to use it on own imagees.

Hi there, we’ve updated the pre-trained model and added instructions for using it with real-captured images. Feel free to give it a try!

If you encounter any issues, please leave a comment—we're here to help. 😃

**Comment by Lyricccco** [comment]
> Okay, model is here, but not instructions how to use it on own imagees.

Hi there! Thank you for your interest.

We’ve updated the code, as well as the instructions for training, testing, and inference, along with pre-trained models and visual results. Feel free to give it a try!

If you encounter any issues, please leave a comment—we're here to help. 😃

**Comment by Lyricccco** [comment]
> Great work ! When will be the pretrained models published

Hi there! Thank you for your interest.

We’ve updated the code, as well as the instructions for training, testing, and inference, along with pre-trained models and visual results. Feel free to give it a try!

If you encounter any issues, please leave a comment—we're here to help. 😃

**Comment by profile838** [comment]
Is there a way to denoise photos without raw captures, for example jpeg format only as input?
Not in pairs (RAW+JPEG)?

**Comment by Lyricccco** [comment]
> Is there a way to denoise photos without raw captures, for example jpeg format only as input? Not in pairs (RAW+JPEG)?

Our method relies on dual-domain denoising, which means it first processes the image in the RAW domain before moving to the sRGB domain. So, unfortunately, denoising with only JPEG input (without RAW) isn’t possible with our current approach. But, denoising with only RAW input is possible, that is, open `'./options/DualDn_Big.yml'` and set BGU in `datasets/val/Real_captured` to `false`
